name: ecomerceapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  get: ^4.7.2
  get_storage: ^2.1.1
  path: ^1.8.3
  share_plus: ^12.0.0
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  lottie: ^3.3.2
  collection: ^1.18.0
  intl: ^0.19.0
  image_picker: ^1.2.0
  google_generative_ai: ^0.4.7
  dash_chat_2: ^0.0.21
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - .env
